### ISSUE TITLE
Add an Iso for Nullable/Maybe

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-nullable#12]
From #8. Something like

```purescript
import Data.Profunctor

isoToMaybe :: forall p a b. Profunctor p => p (Nullable a) (Nullable b) -> p (Maybe a) (Maybe b)
isoToMaybe = dimap toNullable toMaybe 
```

**Comment by hdgarrood** [comment]
Presumably this would not be law-abiding because of the parametricity issue? Not that we shouldn't add this; it probably just wants documenting once we do get around to it.
